import { z } from "zod";

/**
 * Canonical event taxonomy — mirrors the extension's `types/capture-events.ts`
 * `BackendEventType` union plus the section-view types its background script
 * derives from SECTION_ENGAGEMENT messages. Keep the two lists in sync.
 */
export const EVENT_TYPES = [
  "page_view",
  "wishlist_add",
  "wishlist_remove",
  "add_to_cart",
  "remove_from_cart",
  "dwell_milestone",
  "scroll_milestone",
  "details_section_view",
  "material_section_view",
  "size_guide_view",
  "review_section_view",
  "size_selected",
  "colour_selected",
  // Not yet emitted by the extension, but reserved so the API doesn't need
  // a breaking change when these ship (purchase detection is next up):
  "cart_abandon",
  "purchase_confirmed",
  "return_initiated",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

export const eventSchema = z.object({
  // Anonymous, stable per-install identifier generated by the extension
  // (UUID stored in chrome.storage.local on first run). This is how we
  // link events to a shopper before any email/account exists.
  extension_id: z.string().min(1),

  event_type: z.enum(EVENT_TYPES),

  // Product context — present on most event types, optional because
  // session-level events may not have a product.
  product_url: z.string().url().optional(),
  product_name: z.string().optional(),
  product_brand: z.string().optional(),
  product_price: z.number().nonnegative().optional(),
  original_price: z.number().nonnegative().optional(),
  currency: z.string().length(3).optional(), // ISO 4217, e.g. "GBP"
  category: z.string().optional(),
  colour: z.string().optional(),

  // Behavioural measurements — dwell_ms on dwell_milestone events,
  // scroll_pct on scroll_milestone events. Stored in the payload jsonb
  // but validated here because the signals engine depends on them.
  dwell_ms: z.number().nonnegative().optional(),
  scroll_pct: z.number().min(0).max(100).optional(),

  // Client-side timestamp (ms since epoch). Server also stamps created_at,
  // but this preserves ordering if requests arrive out of sequence.
  client_timestamp: z.number().optional(),

  // Catch-all for event-specific fields: sizes, section label, order
  // totals, etc. Kept loose deliberately — the taxonomy is still evolving
  // and we don't want schema changes to require a redeploy every time a
  // new field is added.
  payload: z.record(z.any()).optional(),
});

export type IncomingEvent = z.infer<typeof eventSchema>;

// Batches: the extension queues events client-side (e.g. on SPA navigation)
// and flushes them together rather than firing one request per event.
export const eventBatchSchema = z.object({
  events: z.array(eventSchema).min(1).max(100),
});

export type IncomingEventBatch = z.infer<typeof eventBatchSchema>;
